apps:
- name: chatbot-back-end
  cwd: ./backend-chatbot
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  watch: true
  env:
    PORT: 3001
- name: chatbot-front-end
  cwd: ./frontend-chatbot
  script: npm
  args: "run dev"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3000
